#pragma once
#include <SFML/Graphics.hpp>

struct AnimationData
{
	int frames;
	sf::IntRect rect[16];
	int timer[16];
};

enum AnimationType
{
	PLAYER_WALKING_DOWN,
	PLAYER_WALKING_UP,
	PLAYER_WALKING_RIGHT,
	PLAYER_WALKING_LEFT,
	PLAYER_IDLE_DOWN,
	PLAYER_IDLE_UP,
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	DOCTOR_WALKING_DOWN,
	DOCTOR_WALKING_UP,
	DOCTOR_WALKING_RIGHT,
	DOCTOR_WALKING_LEFT,
	DOCTOR_IDLE_DOWN,
	DOCTOR_IDLE_UP,
	DOCTOR_IDLE_RIGHT,
	DOCTOR_IDLE_LEFT,
	BELT_RIGHT,
	BUTTON_A_PRESS,
	NADA,
	POKEMON,
	PLAGUEDOC_IDLE_DOWN,
	PLAGUEDOC_IDLE_UP,
	PLAGUEDOC_IDLE_LEFT,
	PLAGUEDOC_IDLE_RIGHT,
	PLAGUEDOC_WALKING_LEFT,
	PLAGUEDOC_WALKING_RIGHT,
	PLAGUEDOC_WALKING_UP,
	PLAGUE_DOC_WALKING_DOWN,
	COOLGUY_IDLE_DOWN,
	COOLGUY_IDLE_UP,
	COOLGUY_IDLE_LEFT,
	COOLGUY_IDLE_RIGHT,
	COOLGUY_WALKING_DOWN,
	COOLGUY_WALKING_UP,
	COOLGUY_WALKING_LEFT,
	COOLGUY_WALKING_RIGHT,
	ROOMBA_DOWN,
	ROOMBA_UP,
	ROOMBA_LEFT,
	ROOMBA_RIGHT,
	ROOMBA_DOOR_OPEN,
	ROOMBA_DOOR_CLOSE,
	CAPSULE_OPENING,
	CAPSULE_OPENED,
	CAPSULE_CLOSED,
	CAPSULE_CLOSING,
	SPAWN,
	MARIO_IDLE,
	MARIO_WALK,
	MARIO_TURN,
	MARIO_JUMP,
	MARIO_CROUCH,
	MARIO_ONWALL,
	MARIO_CROUCH_LOOK_UP,
	BAT_FLYING,
	BAT_FLIP,
	BAT_SIESTA,
	BAT_AWAKE,
};


extern AnimationData anim_lib[];
