#include <vector>

enum TerrainTiles {
    GRASS = 0,
    TREE_TOP,
    BUSH,
    SAND,
    TREE_BOTTOM,
    FLOWERS
};

enum CityTiles {
    CGRASS = 0,
    CSAND 
};

const std::vector< std::vector<CityTiles> > citymap ({
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
    {CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS, CityTiles::CGRASS,CityTiles::CGRASS},
});